layers:
  install-fonts:
    - apt-get update
    - apt-get install curl
    - asEnvUser $UHOME/install-fonts.sh
    - rm -rf /tmp/* /var/lib/apt/lists/* /root/.cache/* /usr/share/emacs/25.3/lisp/org/*
  temp-fix-alltheicons:
    - cd $UHOME/.emacs.d/elpa/develop/all-the-icons-2*/
    - rm all-the-icons.el all-the-icons.elc
    - curl https://raw.githubusercontent.com/ubolonton/all-the-icons.el/f85f6ca9bc8d84044a700e137aecacfbdf87603f/all-the-icons.el -o all-the-icons.el
  install-latex:
    - apt-get update
    - apt-get install -y texlive-base texlive-latex-extra latexmk python-pygments gnuplot dvipng
    - apt-get autoremove -y
    - rm -rf /tmp/* /var/lib/apt/lists/* /root/.cache/*
  install-pdf-tools:
    - apt-get update
    - apt-get install automake imagemagick
    - git clone https://github.com/politza/pdf-tools.git
    - cd pdf-tools/server
    - ./autobuild -i ${PWD}
    - make -s install
    - cd ../../
    - rm -rf pdf-tools /tmp/* /var/lib/apt/lists/* /root/.cache/*
  install-pandoc:
    - curl -L https://github.com/jgm/pandoc/releases/download/2.2/pandoc-2.2-1-amd64.deb -o pandoc.deb
    - dpkg -i pandoc.deb
    - apt-get install -f
    - rm pandoc.deb
    - apt-get autoremove -y
    - rm -rf /tmp/* /var/lib/apt/lists/* /root/.cache/*
  install-r:
    - apt-get update
    - apt-get install -y r-base
    - apt-get autoremove -y
    - curl https://codeload.github.com/emacs-ess/ESS/tar.gz/v17.11 --output ess.tar.gz
    - mkdir $UHOME/.emacs.d/private/local/ESS
    - tar xvf ess.tar.gz -C $UHOME/.emacs.d/private/local/ESS --strip-components=1
    - echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile
    - Rscript $UHOME/install-packages.r
    - rm ess.tar.gz $UHOME/install-packages.r
    - rm -rf /tmp/* /var/lib/apt/lists/* /root/.cache/*
  install-deps:
    - install-deps
  pre-install-emacs:
    - echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf
    - apt-get update && apt-get install bash build-essential dbus-x11 fontconfig git gzip language-pack-en-base libgl1-mesa-glx make sudo tar unzip
    - git clone https://github.com/ncopa/su-exec.git /tmp/su-exec
    - cd /tmp/su-exec
    - make
    - chmod 770 su-exec
    - mv ./su-exec /usr/local/sbin/
    - apt-get purge build-essential
    - apt-get autoremove
    - rm -rf /tmp/* /var/lib/apt/lists/* /root/.cache/*
  install-emacs:
    - apt-get update && apt-get install software-properties-common
    - apt-add-repository ppa:kelleyk/emacs
    - apt-get update && apt-get install emacs26
    - apt-get purge software-properties-common
    - rm -rf /tmp/* /var/lib/apt/lists/* /root/.cache/*


images:
  # emacs26:
  #   dockerfile:
  #     from: ubuntu
  #     env_1: NO_AT_BRIDGE=1
  #     env_2: DEBIAN_FRONTEND noninteractive
  #     run_1: pre-install-emacs
  #     run_2: install-emacs
  #     workdir: "${WORKSPACE}"
  #     cmd: ["bash", "-c", "emacs; /bin/bash"]

  plain:
    dockerfile:
      from: spacemacs/emacs25:develop
      copy_1: scripts/install_all_the_icons_fonts.sh $UHOME/install-fonts.sh
      run_1: install-fonts
      copy_2: plain/.spacemacs "$UHOME/.spacemacs"
      copy_3: private "$UHOME/.emacs.d/private"
      run_2: install-deps
      run_3: temp-fix-alltheicons
    spacemacs:
      layers:
        auto-completion:
          variables:
            - auto-completion-enable-snippets-in-popup t
            - auto-completion-tab-key-behavior 'cycle
            - auto-completion-return-key-behavior nil
            - auto-completion-enable-sort-by-usage t
            - auto-completion-complete-with-key-sequence "jk"
            - auto-completion-enable-help-tooltip 'manual
          disabled-for:
            - org
        better-defaults:
        docker:
        git:
        helm:
        org:
        treemacs:
          variables:
            treemacs-use-filewatch-mode t
        markdown:
        ranger:
          variables:
            - ranger-override-dired t
        spell-checking:
          variables:
            - spell-checking-enable-by-default nil
        syntax-checking:
          variables:
            - syntax-checking-enable-by-default nil
        shell:
          variables:
            - shell-default-height 30
            - shell-default-position 'bottom
        vimscript:
        yaml:
        gutils:
      additional-packages:
        - all-the-icons
        - all-the-icons-dired
      user-config: |
        (global-auto-revert-mode t)
        (add-hook 'ranger-mode-hook 'all-the-icons-dired-mode)

        (add-hook 'text-mode-hook 'auto-fill-mode)
        (add-hook 'doc-view-mode-hook 'auto-revert-mode)

        (define-key evil-normal-state-map "+" 'evil-numbers/inc-at-pt)
        (define-key evil-normal-state-map "-" 'evil-numbers/dec-at-pt)

        (global-git-commit-mode t)

  latex:
    dockerfile:
      from: gnoxo/spacemacs-env:plain
      copy: latex/.spacemacs "$UHOME/.spacemacs"
      run_1: install-latex
      run_2: install-pdf-tools
      run_3: install-pandoc
      run_4: install-deps
    spacemacs:
      includes:
        - plain
      layers:
        bibtex:
        latex:
        pandoc:
          variables:
            - pandoc-spacemacs-docker-disable-deps-install t
        pdf:
          variables:
            - pandoc-spacemacs-docker-disable-deps-install t
      additional-packages:
        - cdlatex
      user-config: |
        (add-hook 'org-mode-hook 'turn-on-org-cdlatex)
        (add-to-list 'org-latex-packages-alist '("" "minted"))

        (with-eval-after-load 'org
          (setq org-latex-listings 'minted)
          (setq org-latex-pdf-process '("latexmk -pdflatex='%latex -shell-escape -interaction nonstopmode' -pdf -output-directory=%o -f %f"))

          (org-babel-do-load-languages
          'org-babel-load-languages
          '((emacs-lisp . t)
            (R . t)
            (python . t)))

          (setq org-latex-create-formula-image-program 'imagemagick)
          (setq org-format-latex-options (plist-put org-format-latex-options :scale 1.8))

          (setq org-hide-macro-markers t)
          (setq org-src-fontify-natively t)
          )
  latex-r:
    dockerfile:
      from: gnoxo/spacemacs-env:latex
      copy_1: scripts/install-packages.r $UHOME/install-packages.r
      copy_2: latex-r/.spacemacs $UHOME/.spacemacs
      run_1: install-r
      run_2: install-deps
    spacemacs:
      includes:
        - latex
      layers:
        ess:
          variables:
            - ess-enable-smart-equals t
      user-config: |
        (add-hook 'ess-mode-hook (lambda () (ess-toggle-underscore nil)))
      user-init: |
        (add-to-list 'load-path "~/.emacs.d/private/local/ESS/")
