version: '2.1'

services:
  spacemacs:
    image: gnoxo/spacemacs-env:sp-dev
    build:
      context: .
      dockerfile: Dockerfile.spacemacs
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/run/dbus:/var/run/dbus
      - $WORKSPACE:/mnt/workspace
    environment:
      - DISPLAY=unix$DISPLAY
      - LC_ALL=en_US.UTF-8

  spacemacs-latex:
    image: gnoxo/spacemacs-env:sp-latex
    build:
      context: .
      dockerfile: Dockerfile.l
    extends:
      service: spacemacs
